Imports System.IO
Module ModFunciones
    Public Function Letra_ColumnaExcel(ByVal Columna As Integer) As String
        Select Case Columna
            Case 1
                Return "A"
            Case 2
                Return "B"
            Case 3
                Return "C"
            Case 4
                Return "D"
            Case 5
                Return "E"
            Case 6
                Return "F"
            Case 7
                Return "G"
            Case 8
                Return "H"
            Case 9
                Return "I"
            Case 10
                Return "J"
            Case 11
                Return "K"
            Case 12
                Return "L"
            Case 13
                Return "M"
            Case 14
                Return "N"
            Case 15
                Return "O"
            Case 16
                Return "P"
            Case 17
                Return "Q"
            Case 18
                Return "R"
            Case 19
                Return "S"
            Case 20
                Return "T"
            Case 21
                Return "U"
            Case 22
                Return "V"
            Case 23
                Return "W"
            Case 24
                Return "X"
            Case 25
                Return "Y"
            Case 26
                Return "Z"
            Case 27
                Return "AA"
            Case 28
                Return "AB"
            Case 29
                Return "AC"
            Case 30
                Return "AD"
            Case 31
                Return "AE"
            Case 32
                Return "AF"
            Case 33
                Return "AG"
            Case 34
                Return "AH"
            Case 35
                Return "AI"
            Case 36
                Return "AJ"
            Case 37
                Return "AK"
            Case 38
                Return "AL"
            Case 39
                Return "AM"
            Case 40
                Return "AN"
            Case 41
                Return "AO"
            Case 42
                Return "AP"
            Case 43
                Return "AQ"
            Case 44
                Return "AR"
            Case 45
                Return "AS"
            Case 46
                Return "AT"
            Case 47
                Return "AU"
            Case 48
                Return "AV"
            Case 49
                Return "AW"
            Case 50
                Return "AX"
            Case 51
                Return "AY"
            Case 52
                Return "AZ"
            Case 53
                Return "BA"
            Case 54
                Return "BB"
            Case 55
                Return "BC"
            Case 56
                Return "BD"
            Case 57
                Return "BE"
            Case 58
                Return "BF"
            Case 59
                Return "BG"
            Case 60
                Return "BH"
            Case 61
                Return "BI"
            Case 62
                Return "BJ"
            Case 63
                Return "BK"
            Case 64
                Return "BL"
            Case 65
                Return "BM"
            Case 66
                Return "BN"
            Case 67
                Return "BO"
            Case 68
                Return "BP"
            Case 69
                Return "BQ"
            Case 70
                Return "BR"
            Case 71
                Return "BS"
            Case 72
                Return "BT"
            Case 73
                Return "BU"
            Case 74
                Return "BV"
            Case 75
                Return "BW"
            Case 76
                Return "BX"
            Case 77
                Return "BY"
            Case 78
                Return "BZ"
            Case 79
                Return "CA"
            Case 80
                Return "CB"
            Case 81
                Return "CC"
            Case 82
                Return "CD"
            Case 83
                Return "CE"
            Case 84
                Return "CF"
            Case 85
                Return "CG"
            Case 86
                Return "CH"
            Case 87
                Return "CI"
            Case 88
                Return "CJ"
            Case 89
                Return "CK"
            Case 90
                Return "CL"
            Case 91
                Return "CM"
            Case 92
                Return "CN"
            Case 93
                Return "CO"
            Case 94
                Return "CP"
            Case 95
                Return "CQ"
            Case 96
                Return "CR"
            Case 97
                Return "CS"
            Case 98
                Return "CT"
            Case 99
                Return "CU"
            Case 100
                Return "CV"
            Case 101
                Return "CW"
            Case 102
                Return "CX"
            Case 103
                Return "CY"
            Case 104
                Return "CZ"
            Case 105
                Return "DA"
            Case 106
                Return "DB"
            Case 107
                Return "DC"
            Case 108
                Return "DD"
            Case 109
                Return "DE"
            Case 110
                Return "DF"
            Case 111
                Return "DG"
            Case 112
                Return "DH"
            Case 113
                Return "DI"
            Case 114
                Return "DJ"
            Case 115
                Return "DK"
            Case 116
                Return "DL"
            Case 117
                Return "DM"
            Case 118
                Return "DN"
            Case 119
                Return "DO"
            Case 120
                Return "DP"
            Case 121
                Return "DQ"
            Case 122
                Return "DR"
            Case 123
                Return "DS"
            Case 124
                Return "DT"
            Case 125
                Return "DU"
            Case 126
                Return "DV"
            Case 127
                Return "DW"
            Case 128
                Return "DX"
            Case 129
                Return "DY"
            Case 130
                Return "DZ"
            Case 131
                Return "EA"
            Case 132
                Return "EB"
            Case 133
                Return "EC"
            Case 134
                Return "ED"
            Case 135
                Return "EE"
            Case 136
                Return "EF"
            Case 137
                Return "EG"
            Case 138
                Return "EH"
            Case 139
                Return "EI"
            Case 140
                Return "EJ"
            Case 141
                Return "EK"
            Case 142
                Return "EL"
            Case 143
                Return "EM"
            Case 144
                Return "EN"
            Case 145
                Return "EO"
            Case 146
                Return "EP"
            Case 147
                Return "EQ"
            Case 148
                Return "ER"
            Case 149
                Return "ES"
            Case 150
                Return "ET"
            Case 151
                Return "EU"
            Case 152
                Return "EV"
            Case 153
                Return "EW"
            Case 154
                Return "EX"
            Case 155
                Return "EY"
            Case 156
                Return "EZ"
            Case 157
                Return "FA"
            Case 158
                Return "FB"
            Case 159
                Return "FC"
            Case 160
                Return "FD"
            Case 161
                Return "FE"
            Case 162
                Return "FF"
            Case 163
                Return "FG"
            Case 164
                Return "FH"
            Case 165
                Return "FI"
            Case 166
                Return "FJ"
            Case 167
                Return "FK"
            Case 168
                Return "FL"
            Case 169
                Return "FM"
            Case 170
                Return "FN"
            Case 171
                Return "FO"
            Case 172
                Return "FP"
            Case 173
                Return "FQ"
            Case 174
                Return "FR"
            Case 175
                Return "FS"
            Case 176
                Return "FT"
            Case 177
                Return "FU"
            Case 178
                Return "FV"
            Case 179
                Return "FW"
            Case 180
                Return "FX"
            Case 181
                Return "FY"
            Case 182
                Return "FZ"
            Case 183
                Return "GA"
            Case 184
                Return "GB"
            Case 185
                Return "GC"
            Case 186
                Return "GD"
            Case 187
                Return "GE"
            Case 188
                Return "GF"
            Case 189
                Return "GG"
            Case 190
                Return "GH"
            Case 191
                Return "GI"
            Case 192
                Return "GJ"
            Case 193
                Return "GK"
            Case 194
                Return "GL"
            Case 195
                Return "GM"
            Case 196
                Return "GN"
            Case 197
                Return "GO"
            Case 198
                Return "GP"
            Case 199
                Return "GQ"
            Case 200
                Return "GR"
            Case 201
                Return "GS"
            Case 202
                Return "GT"
            Case 203
                Return "GU"
            Case 204
                Return "GV"
            Case 205
                Return "GW"
            Case 206
                Return "GX"
            Case 207
                Return "GY"
            Case 208
                Return "GZ"
            Case 209
                Return "HA"
            Case 210
                Return "HB"
            Case 211
                Return "HC"
            Case 212
                Return "HD"
            Case 213
                Return "HE"
            Case 214
                Return "HF"
            Case 215
                Return "HG"
            Case 216
                Return "HH"
            Case 217
                Return "HI"
            Case 218
                Return "HJ"
            Case 219
                Return "HK"
            Case 220
                Return "HL"
            Case 221
                Return "HM"
            Case 222
                Return "HN"
            Case 223
                Return "HO"
            Case 224
                Return "HP"
            Case 225
                Return "HQ"
            Case 226
                Return "HR"
            Case 227
                Return "HS"
            Case 228
                Return "HT"
            Case 229
                Return "HU"
            Case 230
                Return "HV"
            Case 231
                Return "HW"
            Case 232
                Return "HX"
            Case 233
                Return "HY"
            Case 234
                Return "HZ"
            Case 235
                Return "IA"
            Case 236
                Return "IB"
            Case 237
                Return "IC"
            Case 238
                Return "ID"
            Case 239
                Return "IE"
            Case 240
                Return "IF"
            Case 241
                Return "IG"
            Case 242
                Return "IH"
            Case 243
                Return "II"
            Case 244
                Return "IJ"
            Case 245
                Return "IK"
            Case 246
                Return "IL"
            Case 247
                Return "IM"
            Case 248
                Return "IN"
            Case 249
                Return "IO"
            Case 250
                Return "IP"
            Case 251
                Return "IQ"
            Case 252
                Return "IR"
            Case 253
                Return "IS"
            Case 254
                Return "IT"
            Case 255
                Return "IU"
            Case 256
                Return "IV"
            Case 257
                Return "IW"
            Case 258
                Return "IX"
            Case 259
                Return "IY"
            Case 260
                Return "IZ"
            Case 261
                Return "JA"
            Case 262
                Return "JB"
            Case 263
                Return "JC"
            Case 264
                Return "JD"
            Case 265
                Return "JE"
            Case 266
                Return "JF"
            Case 267
                Return "JG"
            Case 268
                Return "JH"
            Case 269
                Return "JI"
            Case 270
                Return "JJ"
            Case 271
                Return "JK"
            Case 272
                Return "JL"
            Case 273
                Return "JM"
            Case 274
                Return "JN"
            Case 275
                Return "JO"
            Case 276
                Return "JP"
            Case 277
                Return "JQ"
            Case 278
                Return "JR"
            Case 279
                Return "JS"
            Case 280
                Return "JT"
            Case 281
                Return "JU"
            Case 282
                Return "JV"
            Case 283
                Return "JW"
            Case 284
                Return "JX"
            Case 285
                Return "JY"
            Case 286
                Return "JZ"
            Case 287
                Return "KA"
            Case 288
                Return "KB"
            Case 289
                Return "KC"
            Case 290
                Return "KD"
            Case 291
                Return "KE"
            Case 292
                Return "KF"
            Case 293
                Return "KG"
            Case 294
                Return "KH"
            Case 295
                Return "KI"
            Case 296
                Return "KJ"
            Case 297
                Return "KK"
            Case 298
                Return "KL"
            Case 299
                Return "KM"
            Case 300
                Return "KN"
            Case 301
                Return "KO"
            Case 302
                Return "KP"
            Case 303
                Return "KQ"
            Case 304
                Return "KR"
            Case 305
                Return "KS"
            Case 306
                Return "KT"
            Case 307
                Return "KU"
            Case 308
                Return "KV"
            Case 309
                Return "KW"
            Case 310
                Return "KX"
            Case 311
                Return "KY"
            Case 312
                Return "KZ"
            Case 313
                Return "LA"
            Case 314
                Return "LB"
            Case 315
                Return "LC"
            Case 316
                Return "LD"
            Case 317
                Return "LE"
            Case 318
                Return "LF"
            Case 319
                Return "LG"
            Case 320
                Return "LH"
            Case 321
                Return "LI"
            Case 322
                Return "LJ"
            Case 323
                Return "LK"
            Case 324
                Return "LL"
            Case 325
                Return "LM"
            Case 326
                Return "LN"
            Case 327
                Return "LO"
            Case 328
                Return "LP"
            Case 329
                Return "LQ"
            Case 330
                Return "LR"
            Case 331
                Return "LS"
            Case 332
                Return "LT"
            Case 333
                Return "LU"
            Case 334
                Return "LV"
            Case 335
                Return "LW"
            Case 336
                Return "LX"
            Case 337
                Return "LY"
            Case 338
                Return "LZ"
            Case 339
                Return "MA"
            Case 340
                Return "MB"
            Case 341
                Return "MC"
            Case 342
                Return "MD"
            Case 343
                Return "ME"
            Case 344
                Return "MF"
            Case 345
                Return "MG"
            Case 346
                Return "MH"
            Case 347
                Return "MI"
            Case 348
                Return "MJ"
            Case 349
                Return "MK"
            Case 350
                Return "ML"
            Case 351
                Return "MM"
            Case 352
                Return "MN"
            Case 353
                Return "MO"
            Case 354
                Return "MP"
            Case 355
                Return "MQ"
            Case 356
                Return "MR"
            Case 357
                Return "MS"
            Case 358
                Return "MT"
            Case 359
                Return "MU"
            Case 360
                Return "MV"
            Case 361
                Return "MW"
            Case 362
                Return "MX"
            Case 363
                Return "MY"
            Case 364
                Return "MZ"
            Case 365
                Return "NA"
            Case 366
                Return "NB"
            Case 367
                Return "NC"
            Case 368
                Return "ND"
            Case 369
                Return "NE"
            Case 370
                Return "NF"
            Case 371
                Return "NG"
            Case 372
                Return "NH"
            Case 373
                Return "NI"
            Case 374
                Return "NJ"
            Case 375
                Return "NK"
            Case 376
                Return "NL"
            Case 377
                Return "NM"
            Case 378
                Return "NN"
            Case 379
                Return "NO"
            Case 380
                Return "NP"
            Case 381
                Return "NQ"
            Case 382
                Return "NR"
            Case 383
                Return "NS"
            Case 384
                Return "NT"
            Case 385
                Return "NU"
            Case 386
                Return "NV"
            Case 387
                Return "NW"
            Case 388
                Return "NX"
            Case 389
                Return "NY"
            Case 390
                Return "NZ"
            Case 391
                Return "OA"
            Case 392
                Return "OB"
            Case 393
                Return "OC"
            Case 394
                Return "OD"
            Case 395
                Return "OE"
            Case 396
                Return "OF"
            Case 397
                Return "OG"
            Case 398
                Return "OH"
            Case 399
                Return "OI"
            Case 400
                Return "OJ"
            Case 401
                Return "OK"
            Case 402
                Return "OL"
            Case 403
                Return "OM"
            Case 404
                Return "ON"
            Case 405
                Return "OO"
            Case 406
                Return "OP"
            Case 407
                Return "OQ"
            Case 408
                Return "OR"
            Case 409
                Return "OS"
            Case 410
                Return "OT"
            Case 411
                Return "OU"
            Case 412
                Return "OV"
            Case 413
                Return "OW"
            Case 414
                Return "OX"
            Case 415
                Return "OY"
            Case 416
                Return "OZ"
            Case 417
                Return "PA"
            Case 418
                Return "PB"
            Case 419
                Return "PC"
            Case 420
                Return "PD"
            Case 421
                Return "PE"
            Case 422
                Return "PF"
            Case 423
                Return "PG"
            Case 424
                Return "PH"
            Case 425
                Return "PI"
            Case 426
                Return "PJ"
            Case 427
                Return "PK"
            Case 428
                Return "PL"
            Case 429
                Return "PM"
            Case 430
                Return "PN"
            Case 431
                Return "PO"
            Case 432
                Return "PP"
            Case 433
                Return "PQ"
            Case 434
                Return "PR"
            Case 435
                Return "PS"
            Case 436
                Return "PT"
            Case 437
                Return "PU"
            Case 438
                Return "PV"
            Case 439
                Return "PW"
            Case 440
                Return "PX"
            Case 441
                Return "PY"
            Case 442
                Return "PZ"
            Case 443
                Return "QA"
            Case 444
                Return "QB"
            Case 445
                Return "QC"
            Case 446
                Return "QD"
            Case 447
                Return "QE"
            Case 448
                Return "QF"
            Case 449
                Return "QG"
            Case 450
                Return "QH"
            Case 451
                Return "QI"
            Case 452
                Return "QJ"
            Case 453
                Return "QK"
            Case 454
                Return "QL"
            Case 455
                Return "QM"
            Case 456
                Return "QN"
            Case 457
                Return "QO"
            Case 458
                Return "QP"
            Case 459
                Return "QQ"
            Case 460
                Return "QR"
            Case 461
                Return "QS"
            Case 462
                Return "QT"
            Case 463
                Return "QU"
            Case 464
                Return "QV"
            Case 465
                Return "QW"
            Case 466
                Return "QX"
            Case 467
                Return "QY"
            Case 468
                Return "QZ"
            Case 469
                Return "RA"
            Case 470
                Return "RB"
            Case 471
                Return "RC"
            Case 472
                Return "RD"
            Case 473
                Return "RE"
            Case 474
                Return "RF"
            Case 475
                Return "RG"
            Case 476
                Return "RH"
            Case 477
                Return "RI"
            Case 478
                Return "RJ"
            Case 479
                Return "RK"
            Case 480
                Return "RL"
            Case 481
                Return "RM"
            Case 482
                Return "RN"
            Case 483
                Return "RO"
            Case 484
                Return "RP"
            Case 485
                Return "RQ"
            Case 486
                Return "RR"
            Case 487
                Return "RS"
            Case 488
                Return "RT"
            Case 489
                Return "RU"
            Case 490
                Return "RV"
            Case 491
                Return "RW"
            Case 492
                Return "RX"
            Case 493
                Return "RY"
            Case 494
                Return "RZ"
            Case 495
                Return "SA"
            Case 496
                Return "SB"
            Case 497
                Return "SC"
            Case 498
                Return "SD"
            Case 499
                Return "SE"
            Case 500
                Return "SF"
            Case 501
                Return "SG"
            Case 502
                Return "SH"
            Case 503
                Return "SI"
            Case 504
                Return "SJ"
            Case 505
                Return "SK"
            Case 506
                Return "SL"
            Case 507
                Return "SM"
            Case 508
                Return "SN"
            Case 509
                Return "SO"
            Case 510
                Return "SP"
            Case 511
                Return "SQ"
            Case 512
                Return "SR"
            Case 513
                Return "SS"
            Case 514
                Return "ST"
            Case 515
                Return "SU"
            Case 516
                Return "SV"
            Case 517
                Return "SW"
            Case 518
                Return "SX"
            Case 519
                Return "SY"
            Case 520
                Return "SZ"
            Case 521
                Return "TA"
            Case 522
                Return "TB"
            Case 523
                Return "TC"
            Case 524
                Return "TD"
            Case 525
                Return "TE"
            Case 526
                Return "TF"
            Case 527
                Return "TG"
            Case 528
                Return "TH"
            Case 529
                Return "TI"
            Case 530
                Return "TJ"
            Case 531
                Return "TK"
            Case 532
                Return "TL"
            Case 533
                Return "TM"
            Case 534
                Return "TN"
            Case 535
                Return "TO"
            Case 536
                Return "TP"
            Case 537
                Return "TQ"
            Case 538
                Return "TR"
            Case 539
                Return "TS"
            Case 540
                Return "TT"
            Case 541
                Return "TU"
            Case 542
                Return "TV"
            Case 543
                Return "TW"
            Case 544
                Return "TX"
            Case 545
                Return "TY"
            Case 546
                Return "TZ"
            Case Else
                Return "XFD"
        End Select
    End Function

    Public Function ValidarEntero(ByVal KeyAscii As Integer) As Integer
        If Not ((KeyAscii >= 48 And KeyAscii <= 57) Or KeyAscii = 8) Then
            KeyAscii = 0
            Beep()
        End If
        Return KeyAscii
    End Function
    Public Function ValidarDecimal(ByVal KeyAscii As Integer, ByVal Texto As String) As Integer
        If Chr(KeyAscii) = "." Then

            If Len(Texto) = 0 Then
                If Chr(KeyAscii) = "." Then
                    KeyAscii = 0
                    Return KeyAscii
                    Exit Function
                End If
            End If

            If InStr(1, Texto, ".") <> 0 Then
                KeyAscii = 0
                Return KeyAscii
                Exit Function
            End If
        End If

        If Not ((KeyAscii >= 48 And KeyAscii <= 57) Or KeyAscii = 8 Or Chr(KeyAscii) = ".") Then
            KeyAscii = 0
            Beep()
            Return KeyAscii
            Exit Function
        End If
        Return KeyAscii
    End Function
    Public Function ConvertImageByte(ByVal Ruta As String) As Byte()
        Dim nro As Integer
        Dim fs As New FileStream(Ruta, FileMode.OpenOrCreate, FileAccess.Read)
        nro = fs.Length
        Dim MyData(nro) As Byte
        fs.Read(MyData, 0, fs.Length)
        fs.Close()
        Return MyData
    End Function

    Public Function ObtenerNumeroDeVersionSistema() As String
        Dim NroVersion As String = "00000000.000000"
        Try
            Dim _version As Version = Reflection.Assembly.GetExecutingAssembly().GetName().Version
            Dim _FechaCompilacion As DateTime = New DateTime(2000, 1, 1).AddDays(_version.Build).AddSeconds(_version.Revision * 2)
            NroVersion = _FechaCompilacion.ToString("yyyyMMdd.HHmmss")
        Catch ex As Exception
            MessageBox.Show(ex.Message, msgComacsa, MessageBoxButtons.OK, MessageBoxIcon.Error)
        End Try
        Return NroVersion
    End Function
End Module
